# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-24 19:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_status', models.CharField(max_length=100)),
                ('social_security_number', models.CharField(max_length=100)),
                ('blood_type', models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('life_style', models.CharField(max_length=100)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('home_address', models.CharField(max_length=100)),
                ('home_address_security_countermeasures', models.CharField(max_length=100)),
                ('country_of_origin', models.CharField(max_length=100)),
                ('citizenship', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
