# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imager_images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='profile_pics', verbose_name=imager_images.models.Photo)),
                ('camera_type', models.CharField(default='Beseler', max_length=50)),
                ('self_description', models.CharField(default='', max_length=200)),
                ('photo_style', models.CharField(max_length=50, null=True)),
                ('royalty_fees', models.CharField(max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
