# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import imager_images.models


class Migration(migrations.Migration):

    dependencies = [
        ('imager_profile', '0002_auto_20170711_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics', verbose_name=imager_images.models.Photo),
        ),
    ]
